Repository codesquad-members-2023/Control-G-team-05, pull requests merged in 2023-10, with the labels that each got.

#2 #1 [FE] chore: 프로젝트 초기 세팅
  .idea/.gitignore
  .idea/Control-G-team-05.iml
  .idea/aws.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.js
  fe/src/index.js
Labels: 🔧chore, 🐶 FE

#4 #3 [FE] feat: 메인페이지 화면 구성
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/index.js
  fe/src/routes/MainPage.js
  fe/src/routes/MainPage.module.css
  fe/src/styles/global-styles.css
Labels: 🐶 FE, ✨ feature

#9 #6 [BE] chore: 엔티티 공통 작업
  .gitignore
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/entity/Block.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat_member/entity/ChatMember.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat_message/entity/ChatMessage.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat_room/entity/ChatRoom.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/entity/Group.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/entity/Like.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/entity/Member.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member_group/entity/MemberGroup.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/token/entity/Token.java
  be/controlG/src/main/resources/application-jpa.yml
Labels: ☕️ BE, 🔧chore

#11 Fe/feature/8 메인페이지 화면 구성
  fe/src/App.js
  fe/src/animation/css/SlideInAnimation.module.css
  fe/src/animation/css/TextFadeInAnimation.module.css
  fe/src/animation/js/SlideInAnimation.js
  fe/src/animation/js/TextFadeInAnimation.js
  fe/src/component/css/ImageWithText.module.css
  fe/src/component/css/NavigationBar.module.css
  fe/src/component/css/TopBar.module.css
  fe/src/component/js/CustomTextField.js
  fe/src/component/js/ImageWithText.js
  fe/src/component/js/NavigationBar.js
  fe/src/component/js/TopBar.js
  fe/src/routes/SignInPage.js
  fe/src/routes/SignUpPage.js
  fe/src/routes/SignUpPage.module.css
  fe/src/routes/css/MainPage.module.css
  fe/src/routes/css/SignInPage.module.css
  fe/src/routes/css/SignUpPage.module.css
  fe/src/routes/js/MainPage.js
  fe/src/routes/js/SignInPage.js
  fe/src/routes/js/SignUpPage.js
Labels: 🐶 FE, ✨ feature, ♻️ refactor

#13 #12 [FE] feat: 채팅목록 페이지 구성
  fe/src/App.js
  fe/src/component/css/ChatMember.module.css
  fe/src/component/css/GroupIconWithText.module.css
  fe/src/component/css/TopBar.module.css
  fe/src/component/js/ChatMember.js
  fe/src/component/js/GroupIconWithText.js
  fe/src/component/js/NavigationBar.js
  fe/src/component/js/TopBar.js
  fe/src/routes/css/ChatListPage.module.css
  fe/src/routes/css/MainPage.module.css
  fe/src/routes/js/ChatListPage.js
  fe/src/routes/js/MainPage.js
Labels: 🐶 FE, ✨ feature

#15 Be/chore/#10 예외 리스폰스 테스트 코드 어노테이션 공통작업
  be/controlG/build.gradle
  be/controlG/src/main/java/com/codesquad/controlG/exception/CustomRuntimeException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/CustomException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/MemberException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/handler/GlobalExceptionHandler.java
  be/controlG/src/main/resources/application-jasypt.yml
  be/controlG/src/main/resources/application-localDB.yml
  be/controlG/src/main/resources/application-testDB.yml
  be/controlG/src/main/resources/application.yml
  be/controlG/src/test/java/com/codesquad/controlG/DatabaseCleanup.java
  be/controlG/src/test/java/com/codesquad/controlG/DatabaseInitializerExtension.java
  be/controlG/src/test/java/com/codesquad/controlG/annotation/AcceptanceTest.java
  be/controlG/src/test/java/com/codesquad/controlG/annotation/RepositoryTest.java
  be/controlG/src/test/java/com/codesquad/controlG/annotation/ServiceTest.java
  be/controlG/src/test/resources/schema.sql
Labels: ☕️ BE, 🔧chore

#17 Fe/feature/14 채팅 상세 페이지 구성
  fe/src/App.js
  fe/src/component/css/ChatDetailTopBar.module.css
  fe/src/component/css/ChatMessageBox.module.css
  fe/src/component/js/ChatDetailTopBar.js
  fe/src/component/js/ChatMember.js
  fe/src/component/js/ChatMessageBox.js
  fe/src/component/js/NavigationBar.js
  fe/src/routes/css/ChatDetailPage.module.css
  fe/src/routes/js/ChatDetailPage.js
  fe/src/routes/js/ChatListPage.js
  fe/src/routes/js/SignUpPage.js
  fe/src/styles/global-styles.css
Labels: 🐶 FE, ✨ feature

#19 Be/feature/#16 s3 업로드 공통작업
  be/controlG/build.gradle
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/repository/BlockRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat_member/repository/ChatMemberRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat_message/repository/ChatMessageRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat_room/repository/ChatRoomRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/repository/GroupRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/image/ImageFile.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/image/ImageService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/image/S3Uploader.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/repository/LikeRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/repository/MemberRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member_group/repository/MemberGroupRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/token/repository/TokenRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/ImageException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/handler/GlobalExceptionHandler.java
  be/controlG/src/main/resources/application-aws.yml
  be/controlG/src/main/resources/application.yml
  be/controlG/src/test/java/com/codesquad/controlG/DatabaseCleanup.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/image/ImageServiceTest.java
Labels: 🐱 BE, 🔧chore, ✨ feature

#21 #18 [FE] feat: 프로필 페이지 구성
  fe/src/App.js
  fe/src/component/css/ChatMember.module.css
  fe/src/component/css/ProfileDetail.module.css
  fe/src/component/css/ToggleButton.module.css
  fe/src/component/js/ChatMember.js
  fe/src/component/js/NavigationBar.js
  fe/src/component/js/ProfileDetail.js
  fe/src/component/js/ToggleButton.js
  fe/src/routes/css/ProfilePage.module.css
  fe/src/routes/js/ProfilePage.js
Labels: 🐶 FE, ✨ feature

#25 #24 [BE] feat: 공통 어노테이션 작업
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Auth.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/AuthArgumentResolver.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/AuthenticationContext.java
Labels: 🐱 BE, 🔧chore, ✨ feature

#32 #31 [FE] feat: 그룹 상세페이지 구성
  fe/src/App.js
  fe/src/component/css/GroupProfileInformation.module.css
  fe/src/component/css/TopBarWithCenterText.module.css
  fe/src/component/js/GroupIconWithTextAndButton.js
  fe/src/component/js/GroupProfileInformation.js
  fe/src/component/js/ImageWithText.js
  fe/src/component/js/TopBarWithCenterText.js
  fe/src/routes/css/GroupDetailPage.module.css
  fe/src/routes/js/GroupDetailPage.js
  fe/src/routes/js/SearchPage.js
Labels: 🐶 FE, ✨ feature

#34 #33 [FE] feat: 채팅 로딩 페이지 구성
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/component/js/GroupIconWithTextAndButton.js
  fe/src/component/js/TopBarWithCenterText.js
  fe/src/routes/css/ChatLoadingPage.module.css
  fe/src/routes/js/AddGroupPage.js
  fe/src/routes/js/ChatLoadingPage.js
  fe/src/routes/js/GroupDetailPage.js
  fe/src/routes/js/ProfilePage.js
Labels: 🐶 FE, ✨ feature

#36 #35 [FE] refactor: 네비게이션바 리팩토링
  fe/src/component/css/NavigationBar.module.css
  fe/src/component/js/NavigationBar.js
  fe/src/component/js/NavigationButton.js
Labels: 🐶 FE, ♻️ refactor

#37 #26 [BE] feat: 인증관련 api
  be/controlG/build.gradle
  be/controlG/src/main/java/com/codesquad/controlG/config/FilterConfig.java
  be/controlG/src/main/java/com/codesquad/controlG/config/OauthConfig.java
  be/controlG/src/main/java/com/codesquad/controlG/config/WebConfig.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/InMemoryProviderRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/OauthAdapter.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/OauthAttributes.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/OauthProperties.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/OauthProvider.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/OauthRequester.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/dto/OauthTokenResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/Oauth/dto/UserProfile.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/controller/AuthController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/dto/request/AuthReissueTokenRequest.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/dto/request/AuthSignUpRequest.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/dto/response/AuthLoginResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/dto/response/AuthReissueTokenResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/jwt/Jwt.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/jwt/JwtProvider.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/auth/service/AuthService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/repository/MemberRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/token/entity/Token.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/token/repository/TokenRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/token/service/TokenService.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/JwtException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/LoginMemberNotFoundException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/MemberException.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/MemberNotFoundResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/handler/GlobalExceptionHandler.java
  be/controlG/src/main/java/com/codesquad/controlG/filter/CommonFilter.java
  be/controlG/src/main/java/com/codesquad/controlG/filter/JwtFilter.java
  be/controlG/src/main/java/com/codesquad/controlG/filter/SignupTokenFilter.java
  be/controlG/src/main/java/com/codesquad/controlG/filter/WhiteListUri.java
  be/controlG/src/main/java/com/codesquad/controlG/filter/util/RequestParser.java
  be/controlG/src/main/java/com/codesquad/controlG/redis/RedisProperties.java
  be/controlG/src/main/java/com/codesquad/controlG/redis/config/RedisConfig.java
  be/controlG/src/main/java/com/codesquad/controlG/redis/util/RedisUtil.java
  be/controlG/src/main/resources/application-jwt.yml
  be/controlG/src/main/resources/application-oauth.yml
  be/controlG/src/main/resources/application-redis.yml
  be/controlG/src/main/resources/application.yml
  be/controlG/src/test/java/com/codesquad/controlG/domain/auth/controller/AuthControllerTest.java
Labels: 🐱 BE, ✨ feature

#38 #27 [BE] feat: 그룹 API
  be/controlG/build.gradle
  be/controlG/src/main/java/com/codesquad/controlG/config/QueryDslConfig.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/controller/GroupController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/dto/GroupAddMineRequest.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/dto/GroupCreateRequest.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/dto/GroupDetailResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/entity/Group.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/repository/GroupRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/repository/GroupRepositoryCustom.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/repository/GroupRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/service/GroupService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/entity/Like.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member_group/entity/MemberGroup.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member_group/repository/MemberGroupRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/GroupException.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/group/acceptance/GroupAcceptanceTest.java
  be/controlG/src/test/java/com/codesquad/controlG/fixture/FixtureFactory.java
  be/controlG/src/test/resources/schema.sql
Labels: 🐱 BE, ✨ feature, 🚦test

#40 #23 [BE] feat: 프로필 조회 및 수정
  be/controlG/.gitignore
  be/controlG/build.gradle
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/repository/BlockRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/LikeStatus.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/repository/LikeRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/repository/querydsl/LikeQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/controller/MemberController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/dto/LikedMemberResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/dto/MemberResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/dto/MemberUpdateRequest.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/entity/Member.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/service/MemberService.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/LikeStatusException.java
Labels: 🐱 BE, ✨ feature

#43 #42 [BE] feat: jpa에러 수정 및 cors필터 추가
  be/controlG/src/main/java/com/codesquad/controlG/config/FilterConfig.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/repository/BlockRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/like/repository/LikeRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/controller/MemberController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/service/MemberService.java
  be/controlG/src/main/java/com/codesquad/controlG/filter/CorsFilter.java
Labels: 🐱 BE, 🥺 bug, 🔧chore

#46 #45 [BE] test: 그룹 API 테스트 코드 작성
  be/controlG/src/test/java/com/codesquad/controlG/annotation/AcceptanceTestSupport.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/group/acceptance/GroupAcceptanceTest.java
  be/controlG/src/test/resources/schema.sql
Labels: 🐱 BE, 🚦test

#47 #41 [FE] feat: oauth 로그인 api 연동
  fe/src/App.js
  fe/src/api/auth/oauth.js
  fe/src/api/auth/signup.js
  fe/src/component/js/CustomTextField.js
  fe/src/component/js/ImageWithText.js
  fe/src/component/js/NavigationButton.js
  fe/src/constants/endpoints.js
  fe/src/index.js
  fe/src/routes/js/OauthCallBackPage.js
  fe/src/routes/js/SignInPage.js
  fe/src/routes/js/SignUpPage.js
  fe/src/utils/ParseJwt.js
Labels: 🐶 FE, ✨ feature

#49 #42 [BE] test: 회원 api 인수테스트 작성
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/dto/LikedMemberResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/dto/MemberUpdateRequest.java
  be/controlG/src/test/java/com/codesquad/controlG/annotation/AcceptanceTestSupport.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/member/acceptance/MemberAcceptanceTest.java
  be/controlG/src/test/java/com/codesquad/controlG/fixture/FixtureFactory.java
Labels: 🐱 BE, 🚦test

#51 #42 [BE] test: 인증테스트코드
  be/controlG/src/test/java/com/codesquad/controlG/annotation/AcceptanceTestSupport.java
  be/controlG/src/test/java/com/codesquad/controlG/annotation/ServiceTestSupport.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/auth/controller/AuthAcceptanceTest.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/auth/service/AuthServiceTest.java
  be/controlG/src/test/java/com/codesquad/controlG/fixture/FixtureFactory.java
Labels: 🐱 BE, 🚦test

#55 #54 [BE] refactor: 그룹 조회 리팩토링
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/controller/GroupController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/repository/GroupRepositoryCustom.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/repository/GroupRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/group/service/GroupService.java
  be/controlG/src/test/java/com/codesquad/controlG/domain/group/acceptance/GroupAcceptanceTest.java
  be/controlG/src/test/resources/schema.sql
Labels: 🐱 BE, ♻️ refactor

#56 Fe/feature/#53 내 그룹 리스트 api 연동
  fe/src/api/group/MemberGroupList.js
  fe/src/component/js/SearchInput.js
  fe/src/constants/endpoints.js
  fe/src/routes/css/MainPage.module.css
  fe/src/routes/js/MainPage.js
  fe/src/routes/js/OauthCallBackPage.js
  fe/src/routes/js/SignUpPage.js
Labels: 🐶 FE, ✨ feature

#59 #57 [FE] feat: 전체 그룹 리스트 api 연동
  fe/src/App.js
  fe/src/api/group/GroupList.js
  fe/src/routes/css/SearchPage.module.css
  fe/src/routes/js/MainPage.js
  fe/src/routes/js/SearchPage.js
Labels: 🐶 FE, ✨ feature

#61 #60 [FE] feat: 그룹 상세페이지 api 연동
  fe/src/api/group/GroupDetail.js
  fe/src/component/js/GroupProfileInformation.js
  fe/src/constants/endpoints.js
  fe/src/routes/js/GroupDetailPage.js
  fe/src/routes/js/SearchPage.js
Labels: 🐱 BE, ✨ feature

#63 Fe/feature/#62 그룹 생성 및 그룹 가입 api 연동
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/App.module.css
  fe/src/api/group/AddMemberGroup.js
  fe/src/api/group/CreateGroup.js
  fe/src/component/css/GroupIconWithTextAndButton.module.css
  fe/src/component/css/GroupProfileInformation.module.css
  fe/src/component/js/CustomTextField.js
  fe/src/component/js/GroupProfileInformation.js
  fe/src/constants/endpoints.js
  fe/src/routes/js/AddGroupPage.js
  fe/src/routes/js/GroupDetailPage.js
  fe/src/routes/js/SignInPage.js
  fe/src/styles/global-styles.css
Labels: 🐶 FE, ✨ feature

#65 Fe/feature/#64 프로필 창 api 연결
  fe/src/api/member/MemberLikeList.js
  fe/src/api/member/MemberMatchedList.js
  fe/src/api/member/MemberProfile.js
  fe/src/component/css/ChatMember.module.css
  fe/src/component/css/ProfileDetail.module.css
  fe/src/component/css/ProfileMemberList.module.css
  fe/src/component/css/ToggleButton.module.css
  fe/src/component/js/ChatMember.js
  fe/src/component/js/GroupIconWithTextAndButton.js
  fe/src/component/js/ProfileDetail.js
  fe/src/component/js/ProfileMemberList.js
  fe/src/component/js/ToggleButton.js
  fe/src/constants/endpoints.js
  fe/src/routes/css/ProfilePage.module.css
  fe/src/routes/js/ChatListPage.js
  fe/src/routes/js/ProfilePage.js
  fe/src/styles/global-styles.css
Labels: 🐶 FE, ✨ feature

#69 Fe/feature/#68 채팅방 css 수정
  fe/src/component/css/ChatDetailTopBar.module.css
  fe/src/component/js/ChatDetailTopBar.js
  fe/src/component/js/ProfileDetail.js
  fe/src/routes/css/ChatDetailPage.module.css
  fe/src/routes/js/ChatDetailPage.js
  fe/src/routes/js/ProfilePage.js
  fe/src/routes/js/SearchPage.js
Labels: 🐶 FE, ✨ feature

#74 #71 [FE] feat: 채팅 매칭 api 연동
  fe/src/api/auth/signup.js
  fe/src/api/chat/Matching.js
  fe/src/constants/endpoints.js
  fe/src/routes/css/ChatLoadingPage.module.css
  fe/src/routes/js/AddGroupPage.js
  fe/src/routes/js/ChatLoadingPage.js
  fe/src/routes/js/SignUpPage.js
Labels: 🐶 FE, ✨ feature

#75 #72 [BE] feat: 채팅 상세, 채팅 목록구현
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/repository/BlockRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/repository/querydsl/BlockQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/block/repository/querydsl/BlockQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/controller/ChatController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatInfoMessages.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatInfoPartner.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatInfoResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatListMessages.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatListPartner.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatListResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/ChatRoomRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatMessageQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatMessageQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatRoomQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatRoomQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatRoomService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/RedisChatQueueService.java
Labels: 🐱 BE, ✨ feature

#78 #76 [BE] feat : 채팅방 나가기 구현
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/controller/ChatController.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatInfoMessages.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatInfoPartner.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatListPartner.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/entity/ChatMember.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/ChatMemberRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/ChatMessageRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatMessageQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatMessageQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatRoomQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatMemberService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatRoomService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatService.java
  be/controlG/src/main/java/com/codesquad/controlG/exception/errorcode/ChatException.java
  be/controlG/src/main/java/com/codesquad/controlG/interceptor/StompInterceptor.java
Labels: 🐱 BE, ✨ feature

#81 #77 [FE] feat: 채팅방 상세페이지 api 연동
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/api/chat/ChatDetail.js
  fe/src/api/chat/Matching.js
  fe/src/api/member/MemberLike.js
  fe/src/component/css/ChatDetailTopBar.module.css
  fe/src/component/css/ChatMessageBox.module.css
  fe/src/component/js/ChatDetailTopBar.js
  fe/src/component/js/ChatMessageBox.js
  fe/src/constants/Constant.js
  fe/src/constants/endpoints.js
  fe/src/routes/js/ChatDetailPage.js
  fe/src/routes/js/ChatLoadingPage.js
Labels: 🐶 FE, ✨ feature

#85 #84 [BE] hotfix: 채팅전송 리스폰스 수정, 채팅방 접속자 수 수정
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatInfoMessages.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/dto/response/ChatSendMessageResponse.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/entity/ChatMessage.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/RedisChatMemberService.java
Labels: 🐱 BE, 🥺 bug
