Repository codesquad-members-2023/Control-G-team-05, pull requests merged in 2023-11, with the labels that each got.

#87 #82 [FE] feat: 채팅 전송 api 연동
  fe/package-lock.json
  fe/package.json
  fe/src/api/chat/Stomp.js
  fe/src/component/css/ChatMessageBox.module.css
  fe/src/component/js/ChatDetailTopBar.js
  fe/src/component/js/Modal.js
  fe/src/constants/Constant.js
  fe/src/constants/endpoints.js
  fe/src/routes/css/ChatDetailPage.module.css
  fe/src/routes/css/GroupDetailPage.module.css
  fe/src/routes/js/ChatDetailPage.js
Labels: 🐶 FE, ✨ feature

#89 #88 [FE] feat: 채팅목록 api 연동
  fe/src/api/chat/ChatList.js
  fe/src/component/css/ChatMember.module.css
  fe/src/component/css/ChatMessageBox.module.css
  fe/src/component/css/GroupIconWithText.module.css
  fe/src/component/js/ChatMember.js
  fe/src/component/js/GroupIconWithText.js
  fe/src/constants/Constant.js
  fe/src/constants/endpoints.js
  fe/src/routes/css/ChatListPage.module.css
  fe/src/routes/js/ChatListPage.js
Labels: 🐶 FE, ✨ feature

#93 #90 [FE] feat: SSE 연결 구현
  fe/src/App.js
  fe/src/api/chat/SSE.js
  fe/src/component/css/ChatMember.module.css
  fe/src/component/js/ChatMember.js
  fe/src/component/js/GroupIconWithTextAndButton.js
  fe/src/constants/endpoints.js
  fe/src/routes/js/ChatListPage.js
  fe/src/routes/js/ChatLoadingPage.js
  fe/src/routes/js/GroupDetailPage.js
  fe/src/routes/js/MainPage.js
Labels: 🐶 FE, ✨ feature

#95 Fe/feature/#94 채팅 나가기 구현
  fe/src/api/chat/ChatRoomDelete.js
  fe/src/component/css/ProfileMemberList.module.css
  fe/src/component/js/ChatDetailTopBar.js
  fe/src/component/js/ChatMember.js
  fe/src/component/js/Modal.js
  fe/src/component/js/ProfileMemberList.js
  fe/src/constants/Constant.js
  fe/src/constants/endpoints.js
  fe/src/routes/js/ChatDetailPage.js
  fe/src/routes/js/GroupDetailPage.js
Labels: 🐶 FE, ✨ feature

#97 #92 [BE] hotfix: 배포를 위한 수정
  be/controlG/Dockerfile
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatMessageQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatMessageQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatRoomQueryDslRepository.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/repository/querydsl/ChatRoomQueryDslRepositoryImpl.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatService.java
  be/controlG/src/main/java/com/codesquad/controlG/domain/member/dto/LikedMemberResponse.java
  be/controlG/src/main/resources/application-aws.yml
  be/controlG/src/main/resources/application-prodDB.yml
  be/controlG/src/test/java/com/codesquad/controlG/ControlGApplicationTests.java
  be/controlG/src/test/java/com/codesquad/controlG/DatabaseCleanup.java
  be/controlG/src/test/java/com/codesquad/controlG/annotation/AcceptanceTest.java
  be/controlG/src/test/resources/schema.sql
  nginx/Dockerfile
  nginx/nginx.conf
Labels: 🐱 BE, 🥺 bug

#109 #108 [FE] feat: 채팅창에서-엔터-누를시-메세지를-보내는 기능 구현
  fe/.idea/workspace.xml
  fe/src/api/chat/Stomp.js
  fe/src/routes/css/ChatDetailPage.module.css
  fe/src/routes/js/ChatDetailPage.js
Labels: 🐶 FE, ✨ feature

#118 #117 [FE] 채팅 관련 오류 수정
  fe/src/routes/js/ChatDetailPage.js
Labels: 🐶 FE, ✨ feature

#119 hotfix: 채팅 버그 수정
  be/controlG/src/main/java/com/codesquad/controlG/domain/chat/service/ChatService.java
Labels: 🐱 BE, 🥺 bug

#120 #117 [FE] 채팅 관련 오류 수정 (#118)
  fe/src/routes/js/ChatDetailPage.js
Labels: 🐶 FE, ♻️ refactor

#121 Release fe
  fe/src/routes/js/ChatDetailPage.js
Labels: ♻️ refactor

#123 #122 [FE] 채팅 메세지 box 줄바꿈 리팩토링
  fe/src/api/chat/Stomp.js
  fe/src/component/css/ChatMessageBox.module.css
Labels: 🐶 FE, ♻️ refactor
